# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fus-nboot"
BBFILE_PATTERN_fus-nboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_fus-nboot = "10"
LAYERVERSION_fus-nboot = "1"
LAYERSERIES_COMPAT_fus-nboot = "scarthgap"

#NBOOT settings
NBOOT_MAKE_TARGET = "nboot"

#FSIMX93
PREFERRED_VERSION_firmware-ele-imx:fsimx93 = "2.0.2.1"
PREFERRED_VERSION_imx-boot-firmware-files:fsimx93 = "8.27"
PREFERRED_VERSION_nboot:fsimx93 = "2025.08.1"

#FSIMX8ULP
PREFERRED_VERSION_firmware-ele-imx:fsimx8ulp = "1.3.0"
PREFERRED_VERSION_firmware-upower:fsimx8ulp = "1.3.1"
PREFERRED_VERSION_imx-boot-firmware-files:fsimx8ulp = "8.26"
PREFERRED_VERSION_nboot:fsimx8ulp = "2025.02"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:fsimx8ulp:append = " nboot m33-image"
M33_IMAGE:fsimx8ulp ??= "realtimed"

