# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fus-nboot"
BBFILE_PATTERN_fus-nboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_fus-nboot = "10"
LAYERVERSION_fus-nboot = "1"
LAYERSERIES_COMPAT_fus-nboot = "scarthgap"

